(function(){
 const key='ednivo_public_lead_v1';
 function hasLead(){try{return !!JSON.parse(localStorage.getItem(key)||'null')?.email}catch(e){return false}}
 async function saveLead(data){
  localStorage.setItem(key,JSON.stringify({...data,captured_at:new Date().toISOString()}));
  try{if(window.EdNivoSaveLeadEverywhere)await window.EdNivoSaveLeadEverywhere(data);else{await window.EDNIVO_DB?.ready;if(window.ednivoSupabase)await window.ednivoSupabase.from('leads').insert({name:data.name,email:data.email,phone:data.phone,source:data.source,role:'student'});}}catch(e){console.warn('Lead save:',e)}
 }
 function show(){
  if(hasLead())return;
  const source=document.body.dataset.portal==='calculator'?'score-calculator':'sat-syllabus';
  const o=document.createElement('div');o.id='ednivoLeadGate';o.style.cssText='position:fixed;inset:0;background:rgba(8,25,35,.72);z-index:9999;display:grid;place-items:center;padding:18px';
  o.innerHTML=`<div style="width:min(520px,100%);background:#fff;border-radius:18px;padding:26px;box-shadow:0 24px 70px rgba(0,0,0,.25)"><div style="font-size:12px;font-weight:900;color:#ff6b2c;text-transform:uppercase;letter-spacing:1px">Free Ednivo Resource</div><h2 style="margin:8px 0;font-size:28px">Enter your details to continue</h2><p style="color:#66727d;margin:0 0 18px">Fill this once. On future visits from this browser, you can access the resource directly.</p><form id="leadGateForm" style="display:grid;gap:12px"><label style="font-size:12px;font-weight:800">Name<input id="lgName" required style="width:100%;padding:12px;border:1px solid #dfe5e8;border-radius:9px;margin-top:5px" placeholder="Your full name"></label><label style="font-size:12px;font-weight:800">Email<input id="lgEmail" type="email" required style="width:100%;padding:12px;border:1px solid #dfe5e8;border-radius:9px;margin-top:5px" placeholder="you@example.com"></label><div style="display:grid;grid-template-columns:180px 1fr;gap:8px"><label style="font-size:12px;font-weight:800">Country code<select id="lgDial" style="width:100%;padding:12px;border:1px solid #dfe5e8;border-radius:9px;margin-top:5px"></select></label><label style="font-size:12px;font-weight:800">Mobile<input id="lgPhone" type="tel" required style="width:100%;padding:12px;border:1px solid #dfe5e8;border-radius:9px;margin-top:5px" placeholder="Mobile number"></label></div><button style="padding:13px;border:0;border-radius:9px;background:#ff6b2c;color:#fff;font-weight:900;cursor:pointer">Submit & continue →</button><div id="lgStatus" style="font-size:12px;color:#b74444"></div></form></div>`;
  document.body.appendChild(o);document.body.classList.add('ednivo-lead-gate-open');try{EdNivoCountryFields.fill('_none','lgDial','India')}catch(err){const d=document.getElementById('lgDial');d.innerHTML='<option value="+91">India (+91)</option>'}
  document.getElementById('leadGateForm').onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button'),st=document.getElementById('lgStatus');b.disabled=true;b.textContent='Saving…';const data={name:document.getElementById('lgName').value.trim(),email:document.getElementById('lgEmail').value.trim().toLowerCase(),phone:document.getElementById('lgDial').value+' '+document.getElementById('lgPhone').value.trim(),source};try{await saveLead(data);o.remove();document.body.classList.remove('ednivo-lead-gate-open');document.dispatchEvent(new CustomEvent('ednivo:lead-captured',{detail:data}))}catch(err){st.textContent='Please try again.';b.disabled=false;b.textContent='Submit & continue →'}};
 }
 document.addEventListener('DOMContentLoaded',show);
})();
